spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/doAn?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect